### PR TITLE
fix(data engine): moving pkg/config into pkg/driver/config (#8)

### LINKED ISSUE #8: merge pkg/config with pkg/driver
**Describe the problem/challenge you have**

Merge pkg/config into pkg/driver as the config is driver specific.

### PR DESCRIPTION
**Pull request by OussamaSALAHOUELHADJ**
Signed-off-by: Oussama Salahouelhadj salahouelhadjoussama@gmail.com

moving pkg/comfig into pkg/driver/config
- relinking import statement to the new config package path "pkg/driver/config" in the following files:
	- cmd/main.go
	- pkg/driver/driver.go
	- pkg/lvm/iolimiter.go
	- pkg/lvm/iolimiter_test.go

**Why is this PR required? What issue does it fix?**:
this PR is related to this issue: #8

**What this PR does?**:
change the `config` package path from  `...pkg/comfig` to `...pkg/driver/config` and fixing/relinking to the new path.

**Checklist:**
- [x] Fixes #8
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [x] Commit has unit tests
- [x] Commit has integration tests

### CODE REVIEW

**Comment by pawanpraka1** [comment]
@OussamaSALAHOUELHADJ can you run `make format` command and push the formatting changes in this PR?

**Comment by OussamaSALAHOUELHADJ** [comment]
@pawanpraka1 done!

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Comment by pawanpraka1** [comment]
@OussamaSALAHOUELHADJ Thanks for this PR. Can you DCO sign-off this PR (or let me know your email ID).

**Comment by OussamaSALAHOUELHADJ** [comment]
Signed-off-by: Oussama Salahouelhadj salahouelhadjoussama@gmail.com

**Comment by OussamaSALAHOUELHADJ** [comment]
@pawanpraka1 thank you so much for the opportunity to work on this project, and to learn ❤️

**Pull request merged**
