### PR TITLE
fix readme typo

### PR DESCRIPTION
**Pull request by runzhliu**
fix a few typos

## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:

fix a few typos

**What this PR does?**:

fix a few typos

**Does this PR require any upgrade changes?**:

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
thanks @runzhliu 
As additional step would you mind signing your [git commit ](https://github.com/openebs/lvm-localpv/blob/develop/CONTRIBUTING.md#sign-your-work)?

**Comment by runzhliu** [comment]
> thanks @runzhliu As additional step would you mind signing your [git commit ](https://github.com/openebs/lvm-localpv/blob/develop/CONTRIBUTING.md#sign-your-work)?

sure ;)

**Comment by dsharma-dc** [comment]
~~This PR is a duplicate of #327~~

**Review by avishnu — APPROVED** [review]
Thanks for the PR !!

**Pull request merged**
